plugins {
    id 'grace.build.common'
}

dependencies {
    api project(":grace-datastore-gorm-async")
    api libs.groovy.test.junit5
    runtimeOnly libs.groovy.dateutil
    api libs.junit.jupiter.api
    api libs.junit.platform.runner
    runtimeOnly libs.junit.jupiter.engine
    implementation libs.spock.core
}
