plugins {
    id 'java-library'
    id 'groovy'
    id 'maven-publish'
    id 'signing'
    id 'checkstyle'
    id 'codenarc'
}

version = project.projectVersion
group = "org.graceframework"

repositories {
    mavenCentral()
    gradlePluginPortal()
    if (project.projectVersion.endsWith('-SNAPSHOT')) {
        maven {
            name = 'Maven Central Portal Snapshots'
            url = 'https://central.sonatype.com/repository/maven-snapshots/'

            content {
                includeGroupAndSubgroups 'org.graceframework'
            }
            mavenContent {
                snapshotsOnly()
            }
        }
    }
}

configurations {
    documentation
}


dependencies {
    api libs.groovy.core

    testImplementation libs.groovy.test.junit5
    testImplementation libs.junit.jupiter.api
    testImplementation libs.junit.jupiter.engine
    testImplementation libs.junit.platform.runner
    testImplementation libs.spock.core

    documentation libs.javaparser
    documentation libs.groovy.ant
    documentation libs.groovy.core
}

compileTestGroovy {
    configure(groovyOptions.forkOptions) {
        jvmArgs = [ '-Xmx768m']
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withJavadocJar()
    withSourcesJar()
}

javadoc {
    failOnError = false
}

test {
    useJUnitPlatform()
}

configure([javadoc]) {
    options.encoding "UTF-8"
    options.docEncoding "UTF-8"
    options.charSet "UTF-8"
    options.jFlags "-Xms64M", "-Xmx512M"
}

checkstyle {
    toolVersion = "10.26.1"
    configDirectory.set(rootProject.file("config/checkstyle"))
}

codenarc {
    toolVersion = '3.6.0'
    config = resources.text.fromFile(rootProject.file("config/codenarc/codenarc.groovy"))
}