plugins {
    id 'java-library'
    id 'groovy'
    id 'maven-publish'
    id 'signing'
    id 'eclipse'
    id 'idea'
    alias libs.plugins.grace.doc
    alias libs.plugins.gradle.nexus.publish
}

ext."signing.keyId" = project.hasProperty("signing.keyId") ? project.getProperty('signing.keyId') : System.getenv('SIGNING_KEY')
ext."signing.password" = project.hasProperty("signing.password") ? project.getProperty('signing.password') : System.getenv('SIGNING_PASSPHRASE')
ext."signing.secretKeyRingFile" = project.hasProperty("signing.secretKeyRingFile") ? project.getProperty('signing.secretKeyRingFile') : ("${System.properties['user.home']}${File.separator}.gnupg${File.separator}secring.gpg")
ext.isReleaseVersion = !projectVersion.endsWith("SNAPSHOT")

version = project.projectVersion
group = "org.graceframework"

configurations {
    documentation
}

def cleanTask = project.tasks.findByName('clean')
if (cleanTask == null) {
    task clean(type: Delete) {
        delete(buildDir)
    }
}
else {
    cleanTask.doLast {
        ant.delete(dir: 'build/docs')
    }
}

tasks.withType(Groovydoc) {
    group = 'Documentation'
    docTitle = "Grace Data - ${project.version}"
    destinationDir = project.file('build/docs/manual/api')
    def files = []
    project.rootProject.subprojects
            .findAll { !it.name != 'docs' && !it.name.startsWith('examples') }
            .each { subproject ->
                if(subproject.file('src/main/groovy').exists()) {
                    files += subproject.files('src/main/groovy')
                }
                if(subproject.file('src/main/java').exists()) {
                    files += subproject.files('src/main/java')
                }
            }
    if (project.file('src/main/groovy').exists()) {
        files += project.files('src/main/groovy')
    }
    source = files
    classpath += configurations.documentation
}

docs {
    dependsOn groovydoc
    sourceDir = project.file('src/docs')
}

publishing {
    publications {
        maven(MavenPublication) {
            def projectName = project.name.split('-')*.capitalize().join(' ')
            groupId = project.group
            version = project.version

            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }

            from components.java

            pom {
                name = projectName
                description = "Grace Data : $projectName"
                url = 'https://github.com/graceframework/grace-data'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'rainboyan'
                        name = 'Michael Yan'
                        email = 'rain@rainboyan.com'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/graceframework/grace-data.git'
                    developerConnection = 'scm:git:ssh://github.com:graceframework/grace-data.git'
                    url = 'https://github.com/graceframework/grace-data/'
                }
            }
        }
    }
}

afterEvaluate {
    signing {
        required = isReleaseVersion && gradle.taskGraph.hasTask("publish")
        sign publishing.publications.maven
    }
}

nexusPublishing {
    repositories {
        sonatype {
            def mavenUser = System.getenv("MAVEN_CENTRAL_USER") ?: project.hasProperty("mavenCentralUsername") ? project.mavenCentralUsername : ''
            def mavenPass = System.getenv("MAVEN_CENTRAL_PASSWORD") ?: project.hasProperty("mavenCentralPassword") ? project.mavenCentralPassword : ''
            nexusUrl = uri("https://ossrh-staging-api.central.sonatype.com/service/local/")
            snapshotRepositoryUrl = uri("https://central.sonatype.com/repository/maven-snapshots/")
            username = mavenUser
            password = mavenPass
        }
    }
}
