projectVersion=2024.0.0-SNAPSHOT
commonsValidatorVersion=1.9.0
dependencyManagementPluginVersion=1.1.7
expresslyVersion=5.0.0
graceVersion=2024.0.0-M1
groovyVersion=4.0.27
javaParserCoreVersion=3.26.4
javassistVersion=3.30.2-GA

# Overriding Versions in Grace Bom
# grace-async.version=6.3.0
jakarta-el.version=5.0.1

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true