title=Grace Data
projectDesc=Grace Data Access Framework
projectUrl=https://github.com/graceframework/grace-data
projectVersion=2023.3.0-SNAPSHOT
githubSlug=graceframework/grace-data
developers=Michael Yan
caffeineVersion=3.1.8
commonsValidatorVersion=1.9.0
elApiVersion=4.0.0
elImplVersion=4.0.2
graceAsyncVersion=6.3.0-M1
graceVersion=2023.3.0-M2
groovyVersion=4.0.26
h2Version=2.2.224
hibernateValidatorVersion=8.0.2.Final
jakartaValidationVersion=3.0.2
javaAnnotationApiVersion=2.1.1
javaParserCoreVersion=3.26.2
javassistVersion=3.30.2-GA
jpaVersion=3.1.0
jtaVersion=2.0.1
junitJupiterVersion=5.10.5
junitJupiterPlatformVersion=1.10.5
servletApiVersion=6.0.0
slf4jVersion=2.0.17
spockVersion=2.3-groovy-4.0
springVersion=6.1.18

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true