title=Grace Data
projectDesc=Grace Data Access Framework
projectUrl=https://github.com/graceframework/grace-data
projectVersion=2023.3.0-SNAPSHOT
githubSlug=graceframework/grace-data
developers=Michael Yan
commonsValidatorVersion=1.9.0
dependencyManagementPluginVersion=1.1.7
elImplVersion=4.0.2
graceVersion=2023.3.0-RC1
groovyVersion=4.0.26
javaParserCoreVersion=3.26.2
javassistVersion=3.30.2-GA

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true