dependencies {
    api project(':grace-datastore-gorm')
    api "org.graceframework:grace-core:$graceVersion", {
        exclude group: 'org.graceframework', module: 'grace-datastore-core'
    }
    api("org.graceframework:grace-bootstrap:$graceVersion")
}

project.tasks.withType(Jar) {
    configure {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
}
