/*
 * Copyright 2010-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.grails.datastore.mapping.model;

/**
 * Value generation strategies
 *
 * @author Graeme Rocher
 * @since 6.0
 */
public enum ValueGenerator {
    /**
     * Generated natively from the underlying datastore
     */
    NATIVE,

    /**
     * Using an identity column
     */
    IDENTITY,

    /**
     * Generated through assignment
     */
    ASSIGNED,

    /**
     * Generated by the datastore implementation
     */
    GENERATED,

    /**
     * The default generated
     */
    AUTO,

    /**
     * Generated from a sequence
     */
    SEQUENCE,

    /**
     * A generator that uses a HILO algorithm
     */
    HILO,

    /**
     * A generator that uses a sequence and a HILO algorithm
     */
    SEQHILO,

    /**
     * A generator that uses an auto-increment column
     */
    INCREMENT,

    /**
     * A generator that uses UUIDs
     */
    UUID,

    /**
     * A generator that uses UUID2s
     */
    UUID2,

    /**
     * uses a database-generated GUID string on MS SQL Server and MySQL.
     */
    GUID,

    /**
     * use the identifier of another object
     */
    FOREIGN,

    /**
     * Generates the id by selecting from a row using a unique key
     */
    SELECT,

    /**
     * Custom value generation strategy
     */
    CUSTOM

}
