plugins {
    id 'grace.build.common'
}

dependencies {
    api project(":grace-datastore-core")
    api project(":grace-datastore-gorm")

    implementation libs.caffeine
    testImplementation project(":grace-datastore-gorm-tck")
    testImplementation libs.groovy.json
    testRuntimeOnly libs.spring.aop
}
