plugins {
    id 'grace.build.common'
}

dependencies {
    api project(":grace-datastore-core")
    api project(":grace-datastore-gorm-validation")

    implementation libs.slf4j.api
    compileOnly libs.jakarta.el
    compileOnly libs.jakarta.validation
    compileOnly libs.hibernate.validator
    compileOnly libs.spring.core
    compileOnly libs.spring.jdbc
    compileOnly libs.spring.web
    testImplementation libs.spring.jdbc
    testImplementation libs.hibernate.validator
    testImplementation libs.jakarta.el
    testImplementation libs.jakarta.validation
    testRuntimeOnly libs.eclipse.expressly
    testRuntimeOnly libs.h2
}
