plugins {
    id 'grace.build.common'
}

dependencies {
    api libs.jakarta.annotation.api
    api libs.jakarta.transaction
    api libs.jakarta.persistence.api
    api libs.slf4j.api
    api libs.slf4j.jcl
    api libs.spring.context
    api libs.spring.core
    api libs.spring.beans
    api libs.spring.tx
    implementation libs.caffeine
    compileOnly libs.javassist

    testImplementation project(":grace-datastore-gorm")
    testImplementation libs.spring.context
    testImplementation libs.spring.web
}
