dependencies {
    api project(":grace-datastore-core")
    api "org.springframework:spring-web"
    api "org.springframework:spring-context"
    compileOnly("jakarta.servlet:jakarta.servlet-api")

    testImplementation("jakarta.servlet:jakarta.servlet-api")
    testImplementation "org.springframework:spring-test"
}
